labels = [
    "mr_stabs_mk1",
    "mr_stabs_mk2",
    "mrs_buff_mk1",
    "mrs_buff_mk2",
    "robot",
    "referee",
]

[keypoint_names]
"mr_stabs_mk1" = ["front", "back"]
"mr_stabs_mk2" = ["front", "back"]
"mrs_buff_mk1" = ["front", "back"]
"mrs_buff_mk2" = ["front", "back"]
"robot" = ["front", "back"]
"referee" = ["front", "back"]
