[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py311']

[tool.ruff]
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
]
lint.ignore = [
    "E402", # Module level import not at top of file
    "Q003", # avoidable-escaped-quote
]
fix = true
lint.unfixable = [
    "F401", # unused imports
    "F841", # unused variables
]
line-length = 120
lint.select = [
    "C9", # mccabe complexity
    "E", # pycodestyle error
    "F", # pyflakes
    "N", # pep8-naming
    "Q", # flake8-quotes
    "W", # pycodestyle warnings
    "I", # isort
]

[tool.ruff.lint.flake8-quotes]
multiline-quotes = "double"
avoid-escape = false
inline-quotes = "double"

[tool.ruff.lint.mccabe]
max-complexity = 20
