#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

SCRIPT_DIR = os.path.join(BASE_DIR, "..", "detection")
os.chdir(SCRIPT_DIR)


if __name__ == "__main__":
    from metrics_tool import main

    main()
