#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
import os
import sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

SCRIPT_DIR = os.path.join(BASE_DIR, "..", "recorder")
os.chdir(SCRIPT_DIR)

sys.path.append(SCRIPT_DIR)

if __name__ == "__main__":
    from app.main import main  # type: ignore

    main()
