target_tick_rate = 60.0

[camera]
type = "LightSimulatedCamera"

[field_request]
stale_image_timeout = 2.0

[field_filter]
type = "SimulatedFieldFilter"

[field_segmentation]
type = "NoopSegmentation"

[ros]
log = true
exclude_filters = [
    "/camera_0/simulated_segmentation",
    "/camera_0/robot/debug_image",
    "/camera_0/rgb/camera_info",
    "/camera_0/rgb/image_raw",
    "/camera_0/layer/image_raw",
    "/camera_0/depth/depth_registered",
    "/camera_0/robot/segmentation",
    "/camera_0/robot/keypoints",
    "/perception/heartbeat",
    "/camera_0/simulated_field_result",
    "/camera_0/ground_truth/robots",
]

[robot_keypoint]
type = "SimulatedKeypoint"
debug = false

[robot_keypoint.model_to_system_labels.mapping]
"mr_stabs_mk1" = "robot"
"mr_stabs_mk2" = "controlled_robot"
"mrs_buff_mk1" = "friendly_robot"
"mrs_buff_mk2" = "friendly_robot"
"mini_bot" = "controlled_robot"
"main_bot" = "friendly_robot"
"robot" = "robot"
"opponent_1" = "robot"
"referee" = "referee"
