target_tick_rate = 60.0

[camera]
type = "ZedCamera"
serial_number = 33234316

[field_segmentation]
model_path = "data/models/field_deeplabv3_mbv3_2024-06-17.torchscript"
metadata_path = "data/models/field_deeplabv3_mbv3_2024-06-17.json"

[robot_keypoint]
type = "YoloKeypoint"
