target_tick_rate = 60.0

[camera]
type = "ZedCamera"
serial_number = 33234316  # polarlized
# serial_number = 33452020  # non-polarlized
fps = 60
resolution = "mode_vga"

[camera.video_settings]
brightness = 4
contrast = 4
hue = 0
saturation = 4
sharpness = 4
gamma = 5
gain = 97
exposure = 33
aec_agc = 1
whitebalance_temperature = 4700
whitebalance_auto = 1

[field_filter]
type = "PointCloudFieldFilter"

[field_segmentation]
type = "SemanticSegmentation"
debug = true
model_path = "field_deeplabv3_r50_2024-09-05.torchscript"
metadata_path = "field_deeplabv3_r50_2024-09-05.json"

[field_segmentation.model_to_system_labels.mapping]
"field" = "field"
"background" = "background"

[ros]
log = false
exclude_filters = [
    "/camera_0/simulated_segmentation",
    "/camera_0/robot/debug_image",
    "/camera_0/rgb/camera_info",
    "/camera_0/rgb/image_raw",
    "/camera_0/layer/image_raw",
    "/camera_0/depth/depth_registered",
    "/camera_0/robot/segmentation",
    "/perception/heartbeat",
]

[robot_keypoint]
type = "YoloKeypoint"
debug_image = true
threshold = 0.65
model_path = "yolov8n-pose_2024-09-19.pt"
metadata_path = "yolov8n-pose_2024-09-19.json"

[robot_keypoint.model_to_system_labels.mapping]
"mr_stabs_mk1" = "controlled_robot"
"mr_stabs_mk2" = "controlled_robot"
"mrs_buff_mk1" = "friendly_robot"
"mrs_buff_mk2" = "friendly_robot"
"robot" = "robot"
"referee" = "referee"
