target_tick_rate = 60.0

[camera]
type = "ZedCamera"
serial_number = 33234316

[field_filter]
type = "PointCloudFieldFilter"

[field_segmentation]
type = "SemanticSegmentation"
debug = true
model_path = "field_deeplabv3_mbv3_2024-07-24.torchscript"
metadata_path = "field_deeplabv3_mbv3_2024-07-24.json"

[field_segmentation.model_to_system_labels.mapping]
"field" = "field"
"background" = "background"

[ros]
log = false
exclude_filters = [
    "/camera_0/simulated_segmentation",
    "/camera_0/robot/debug_image",
    "/camera_0/rgb/camera_info",
    "/camera_0/rgb/image_raw",
    "/camera_0/layer/image_raw",
    "/camera_0/depth/depth_registered",
    "/camera_0/robot/segmentation",
    "/perception/heartbeat",
]

[robot_keypoint]
type = "YoloKeypoint"
model_path = "yolov8-pose_2024-07-24.pt"
metadata_path = "yolov8-pose_2024-07-24.json"

[robot_keypoint.model_to_system_labels.mapping]
"mr_stabs_mk1" = "controlled_robot"
"mr_stabs_mk2" = "controlled_robot"
"mrs_buff_mk1" = "friendly_robot"
"mrs_buff_mk2" = "friendly_robot"
"robot" = "robot"
"referee" = "referee"
