target_tick_rate = 60.0

[camera]
type = "SvoPlaybackCamera"
# svo_name = "mini_bot_2024-10-25T12-25-28"
# svo_name = "mini_bot_2024-10-25T12-41-20"
# svo_name = "mini_bot_2024-10-25T13-51-16"
svo_name = "mini_bot_2024-10-26T11-30-53"
start_time = 0.0

[field_filter]
type = "PointCloudFieldFilter"

[field_request]
stale_image_timeout = 2.0

[field_segmentation]
type = "SemanticSegmentation"
debug = true
model_path = "field_deeplabv3_r50_2024-09-05.torchscript"

[field_segmentation.model_to_system_labels.mapping]
"field" = "field"
"background" = "background"

[ros]
log = false
exclude_filters = [
    "/camera_0/simulated_segmentation",
    "/camera_0/robot/debug_image",
    "/camera_0/rgb/camera_info",
    "/camera_0/rgb/image_raw",
    "/camera_0/layer/image_raw",
    "/camera_0/depth/depth_registered",
    "/camera_0/robot/segmentation",
    "/perception/heartbeat",
]

[robot_keypoint]
type = "YoloKeypoint"
debug_image = true
threshold = 0.75
model_path = "yolo11x-pose-scratch_2024-10-26.pt"

[robot_keypoint.model_to_system_labels.mapping]
"mr_stabs_mk1" = ""
"mr_stabs_mk2" = "controlled_robot"
"mrs_buff_mk1" = ""
"mrs_buff_mk2" = "friendly_robot"
"robot" = "robot"
"referee" = "referee"
