target_tick_rate = 60.0

[camera]
type = "SimulatedCamera"

[field_request]
stale_image_timeout = 2.0

[field_filter]
type = "PointCloudFieldFilter"

[field_segmentation]
type = "SemanticSegmentation"
debug = true
model_path = "field_deeplabv3_r50_2024-09-05.torchscript"
metadata_path = "field_deeplabv3_r50_2024-09-05.json"

[field_segmentation.model_to_system_labels.mapping]
"field" = "field"
"background" = "background"

[ros]
log = true
exclude_filters = [
    "/camera_0/field/debug_image",
    # "/camera_0/field/point_cloud",
    # "/camera_0/field/segmentation",
    # "/camera_0/point_cloud/cloud_registered",
    "/camera_0/robot/debug_image",
    # "/camera_0/robot/keypoints",
    # "/perception/field/response",
    # "/camera_0/depth/depth_registered",
    # "/camera_0/ground_truth/robots",
    # "/camera_0/layer/image_raw",
    # "/camera_0/rgb/camera_info",
    # "/camera_0/rgb/image_raw",
    # "/camera_0/simulated_segmentation",
    # "/perception/field/request",
    "/perception/heartbeat",
]

# [robot_keypoint]
# type = "SimulatedKeypoint"

[robot_keypoint]
type = "YoloKeypoint"
# debug = true
model_path = "yolov8n-pose_2024-09-02.pt"
metadata_path = "yolov8n-pose_2024-09-02.json"

[robot_keypoint.model_to_system_labels.mapping]
"mr_stabs_mk1" = "controlled_robot"
"mr_stabs_mk2" = "controlled_robot"
"mrs_buff_mk1" = "friendly_robot"
"mrs_buff_mk2" = "friendly_robot"
"mini_bot" = "controlled_robot"
"main_bot" = "friendly_robot"
"robot" = "robot"
"opponent_1" = "robot"
"referee" = "referee"
