[camera]
type = "SimulatedCamera"

[field_filter]
type = "SimulatedFieldFilter"

[field_request]
stale_image_timeout = 2.0

[rosbridge]
log = true
exclude_filters = [
    "/camera_0/simulated_segmentation",
    "/camera_0/robot/debug_image",
    "/camera_0/rgb/camera_info",
    "/camera_0/rgb/image_rect_color/compressed",
    "/camera_0/layer/image_raw/compressed",
    "/camera_0/depth/depth_registered/compressed",
    "/perception/heartbeat",
]

[field_segmentation]
type = "SimulatedSegmentation"

[field_segmentation.simulated_to_real_labels]
"Field" = "field"

[robot_segmentation]
type = "SimulatedSegmentation"

[robot_segmentation.simulated_to_real_labels]
"Mini bot" = "controlled_robot"
"Main bot" = "friendly_robot"
"Enemy bot" = "robot"
"Referee" = "referee"
