target_tick_rate = 60.0

[camera]
type = "SimulatedCamera"

[field_filter]
# type = "SimulatedFieldFilter"
type = "PointCloudFieldFilter"

[field_request]
stale_image_timeout = 2.0

[field_segmentation]
type = "SimulatedSegmentation"

[field_segmentation.model_to_system_labels.mapping]
"field" = "field"

[ros]
log = true
exclude_filters = [
    "/camera_0/field/debug_image",
    # "/camera_0/field/point_cloud",
    # "/camera_0/field/segmentation",
    # "/camera_0/point_cloud/cloud_registered",
    "/camera_0/robot/debug_image",
    # "/camera_0/robot/keypoints",
    # "/perception/field/response",
    # "/camera_0/depth/depth_registered",
    # "/camera_0/ground_truth/robots",
    # "/camera_0/layer/image_raw",
    # "/camera_0/rgb/camera_info",
    # "/camera_0/rgb/image_raw",
    # "/camera_0/simulated_segmentation",
    # "/perception/field/request",
    "/perception/heartbeat",
]

# [robot_keypoint]
# type = "SimulatedKeypoint"

[robot_keypoint]
type = "YoloKeypoint"
model_path = "yolov8-pose_2024-08-25.pt"
metadata_path = "yolov8-pose_2024-08-25.json"


[robot_keypoint.model_to_system_labels.mapping]
"mini_bot" = "controlled_robot"
"main_bot" = "friendly_robot"
"robot" = "robot"
"opponent_1" = "robot"
"referee" = "referee"
