target_tick_rate = 10.0

[camera]
type = "SimulatedCamera"

[field_filter]
# type = "SimulatedFieldFilter"
type = "RansacFieldFilter"

[field_request]
stale_image_timeout = 2.0

[field_segmentation]
type = "SimulatedSegmentation"

[field_segmentation.simulated_to_real_labels]
"Field" = "field"

[ros]
log = false
exclude_filters = [
    "/camera_0/simulated_segmentation",
    "/camera_0/robot/debug_image",
    "/camera_0/rgb/camera_info",
    "/camera_0/rgb/image_raw",
    "/camera_0/layer/image_raw",
    "/camera_0/depth/depth_registered",
    "/camera_0/robot/segmentation",
    "/perception/heartbeat",
]

[robot_keypoint]
type = "SimulatedKeypoint"

[robot_keypoint.simulated_to_real_labels]
"mini_bot" = "controlled_robot"
"main_bot" = "friendly_robot"
"opponent_1" = "robot"
"referee" = "referee"
