//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class BehaviorModeMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/BehaviorMode";
        public override string RosMessageName => k_RosMessageName;

        public uint mode;

        public BehaviorModeMsg()
        {
            this.mode = 0;
        }

        public BehaviorModeMsg(uint mode)
        {
            this.mode = mode;
        }

        public static BehaviorModeMsg Deserialize(MessageDeserializer deserializer) => new BehaviorModeMsg(deserializer);

        private BehaviorModeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
        }

        public override string ToString()
        {
            return "BehaviorModeMsg: " +
            "\nmode: " + mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
