//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class CageSizeMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/CageSize";
        public override string RosMessageName => k_RosMessageName;

        public const byte CAGE_3LB = 0;
        public byte size;

        public CageSizeMsg()
        {
            this.size = 0;
        }

        public CageSizeMsg(byte size)
        {
            this.size = size;
        }

        public static CageSizeMsg Deserialize(MessageDeserializer deserializer) => new CageSizeMsg(deserializer);

        private CageSizeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.size);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.size);
        }

        public override string ToString()
        {
            return "CageSizeMsg: " +
            "\nsize: " + size.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
