//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class CageCornerMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/CageCorner";
        public override string RosMessageName => k_RosMessageName;

        public byte type;

        public CageCornerMsg()
        {
            this.type = 0;
        }

        public CageCornerMsg(byte type)
        {
            this.type = type;
        }

        public static CageCornerMsg Deserialize(MessageDeserializer deserializer) => new CageCornerMsg(deserializer);

        private CageCornerMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "CageCornerMsg: " +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
