//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class CollisionInfoMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/CollisionInfo";
        public override string RosMessageName => k_RosMessageName;

        public string source_object;
        public string collision_with;

        public CollisionInfoMsg()
        {
            this.source_object = "";
            this.collision_with = "";
        }

        public CollisionInfoMsg(string source_object, string collision_with)
        {
            this.source_object = source_object;
            this.collision_with = collision_with;
        }

        public static CollisionInfoMsg Deserialize(MessageDeserializer deserializer) => new CollisionInfoMsg(deserializer);

        private CollisionInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.source_object);
            deserializer.Read(out this.collision_with);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.source_object);
            serializer.Write(this.collision_with);
        }

        public override string ToString()
        {
            return "CollisionInfoMsg: " +
            "\nsource_object: " + source_object.ToString() +
            "\ncollision_with: " + collision_with.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
