//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class ConfigureSimulationMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/ConfigureSimulation";
        public override string RosMessageName => k_RosMessageName;

        public ScenarioConfigMsg scenario;
        public ObjectiveConfigMsg[] objectives;

        public ConfigureSimulationMsg()
        {
            this.scenario = new ScenarioConfigMsg();
            this.objectives = new ObjectiveConfigMsg[0];
        }

        public ConfigureSimulationMsg(ScenarioConfigMsg scenario, ObjectiveConfigMsg[] objectives)
        {
            this.scenario = scenario;
            this.objectives = objectives;
        }

        public static ConfigureSimulationMsg Deserialize(MessageDeserializer deserializer) => new ConfigureSimulationMsg(deserializer);

        private ConfigureSimulationMsg(MessageDeserializer deserializer)
        {
            this.scenario = ScenarioConfigMsg.Deserialize(deserializer);
            deserializer.Read(out this.objectives, ObjectiveConfigMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.scenario);
            serializer.WriteLength(this.objectives);
            serializer.Write(this.objectives);
        }

        public override string ToString()
        {
            return "ConfigureSimulationMsg: " +
            "\nscenario: " + scenario.ToString() +
            "\nobjectives: " + System.String.Join(", ", objectives.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
