//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class ConfiguredOpponentsMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/ConfiguredOpponents";
        public override string RosMessageName => k_RosMessageName;

        public string[] names;

        public ConfiguredOpponentsMsg()
        {
            this.names = new string[0];
        }

        public ConfiguredOpponentsMsg(string[] names)
        {
            this.names = names;
        }

        public static ConfiguredOpponentsMsg Deserialize(MessageDeserializer deserializer) => new ConfiguredOpponentsMsg(deserializer);

        private ConfiguredOpponentsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.names, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
        }

        public override string ToString()
        {
            return "ConfiguredOpponentsMsg: " +
            "\nnames: " + System.String.Join(", ", names.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
