//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class KeypointInstanceArrayMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/KeypointInstanceArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public uint height;
        public uint width;
        public KeypointInstanceMsg[] instances;

        public KeypointInstanceArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.height = 0;
            this.width = 0;
            this.instances = new KeypointInstanceMsg[0];
        }

        public KeypointInstanceArrayMsg(Std.HeaderMsg header, uint height, uint width, KeypointInstanceMsg[] instances)
        {
            this.header = header;
            this.height = height;
            this.width = width;
            this.instances = instances;
        }

        public static KeypointInstanceArrayMsg Deserialize(MessageDeserializer deserializer) => new KeypointInstanceArrayMsg(deserializer);

        private KeypointInstanceArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.height);
            deserializer.Read(out this.width);
            deserializer.Read(out this.instances, KeypointInstanceMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.height);
            serializer.Write(this.width);
            serializer.WriteLength(this.instances);
            serializer.Write(this.instances);
        }

        public override string ToString()
        {
            return "KeypointInstanceArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nheight: " + height.ToString() +
            "\nwidth: " + width.ToString() +
            "\ninstances: " + System.String.Join(", ", instances.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
