//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class KeypointInstanceMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/KeypointInstance";
        public override string RosMessageName => k_RosMessageName;

        public UVKeypointMsg[] keypoints;
        public string[] names;
        public float score;
        public string label;
        public uint class_index;
        public uint object_index;

        public KeypointInstanceMsg()
        {
            this.keypoints = new UVKeypointMsg[0];
            this.names = new string[0];
            this.score = 0.0f;
            this.label = "";
            this.class_index = 0;
            this.object_index = 0;
        }

        public KeypointInstanceMsg(UVKeypointMsg[] keypoints, string[] names, float score, string label, uint class_index, uint object_index)
        {
            this.keypoints = keypoints;
            this.names = names;
            this.score = score;
            this.label = label;
            this.class_index = class_index;
            this.object_index = object_index;
        }

        public static KeypointInstanceMsg Deserialize(MessageDeserializer deserializer) => new KeypointInstanceMsg(deserializer);

        private KeypointInstanceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.keypoints, UVKeypointMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.names, deserializer.ReadLength());
            deserializer.Read(out this.score);
            deserializer.Read(out this.label);
            deserializer.Read(out this.class_index);
            deserializer.Read(out this.object_index);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.keypoints);
            serializer.Write(this.keypoints);
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
            serializer.Write(this.score);
            serializer.Write(this.label);
            serializer.Write(this.class_index);
            serializer.Write(this.object_index);
        }

        public override string ToString()
        {
            return "KeypointInstanceMsg: " +
            "\nkeypoints: " + System.String.Join(", ", keypoints.ToList()) +
            "\nnames: " + System.String.Join(", ", names.ToList()) +
            "\nscore: " + score.ToString() +
            "\nlabel: " + label.ToString() +
            "\nclass_index: " + class_index.ToString() +
            "\nobject_index: " + object_index.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
