//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class LabelsMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/Labels";
        public override string RosMessageName => k_RosMessageName;

        public string[] labels;
        public uint[] ids;

        public LabelsMsg()
        {
            this.labels = new string[0];
            this.ids = new uint[0];
        }

        public LabelsMsg(string[] labels, uint[] ids)
        {
            this.labels = labels;
            this.ids = ids;
        }

        public static LabelsMsg Deserialize(MessageDeserializer deserializer) => new LabelsMsg(deserializer);

        private LabelsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.labels, deserializer.ReadLength());
            deserializer.Read(out this.ids, sizeof(uint), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.labels);
            serializer.Write(this.labels);
            serializer.WriteLength(this.ids);
            serializer.Write(this.ids);
        }

        public override string ToString()
        {
            return "LabelsMsg: " +
            "\nlabels: " + System.String.Join(", ", labels.ToList()) +
            "\nids: " + System.String.Join(", ", ids.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
