//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class MotorVelocitiesMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/MotorVelocities";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double[] velocities;

        public MotorVelocitiesMsg()
        {
            this.header = new Std.HeaderMsg();
            this.velocities = new double[0];
        }

        public MotorVelocitiesMsg(Std.HeaderMsg header, double[] velocities)
        {
            this.header = header;
            this.velocities = velocities;
        }

        public static MotorVelocitiesMsg Deserialize(MessageDeserializer deserializer) => new MotorVelocitiesMsg(deserializer);

        private MotorVelocitiesMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.velocities, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.velocities);
            serializer.Write(this.velocities);
        }

        public override string ToString()
        {
            return "MotorVelocitiesMsg: " +
            "\nheader: " + header.ToString() +
            "\nvelocities: " + System.String.Join(", ", velocities.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
