//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class RobotConfigMsgMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/RobotConfigMsg";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public string team;
        public TagConfigMsgMsg[] tags;
        public double radius;

        public RobotConfigMsgMsg()
        {
            this.name = "";
            this.team = "";
            this.tags = new TagConfigMsgMsg[0];
            this.radius = 0.0;
        }

        public RobotConfigMsgMsg(string name, string team, TagConfigMsgMsg[] tags, double radius)
        {
            this.name = name;
            this.team = team;
            this.tags = tags;
            this.radius = radius;
        }

        public static RobotConfigMsgMsg Deserialize(MessageDeserializer deserializer) => new RobotConfigMsgMsg(deserializer);

        private RobotConfigMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.team);
            deserializer.Read(out this.tags, TagConfigMsgMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.radius);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.team);
            serializer.WriteLength(this.tags);
            serializer.Write(this.tags);
            serializer.Write(this.radius);
        }

        public override string ToString()
        {
            return "RobotConfigMsgMsg: " +
            "\nname: " + name.ToString() +
            "\nteam: " + team.ToString() +
            "\ntags: " + System.String.Join(", ", tags.ToList()) +
            "\nradius: " + radius.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
