//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class SimulationConfigMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/SimulationConfig";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public string json_data;

        public SimulationConfigMsg()
        {
            this.name = "";
            this.json_data = "";
        }

        public SimulationConfigMsg(string name, string json_data)
        {
            this.name = name;
            this.json_data = json_data;
        }

        public static SimulationConfigMsg Deserialize(MessageDeserializer deserializer) => new SimulationConfigMsg(deserializer);

        private SimulationConfigMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.json_data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.json_data);
        }

        public override string ToString()
        {
            return "SimulationConfigMsg: " +
            "\nname: " + name.ToString() +
            "\njson_data: " + json_data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
