//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class SystemSummaryMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/SystemSummary";
        public override string RosMessageName => k_RosMessageName;

        public string robot;
        public string map;
        public string version;

        public SystemSummaryMsg()
        {
            this.robot = "";
            this.map = "";
            this.version = "";
        }

        public SystemSummaryMsg(string robot, string map, string version)
        {
            this.robot = robot;
            this.map = map;
            this.version = version;
        }

        public static SystemSummaryMsg Deserialize(MessageDeserializer deserializer) => new SystemSummaryMsg(deserializer);

        private SystemSummaryMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot);
            deserializer.Read(out this.map);
            deserializer.Read(out this.version);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot);
            serializer.Write(this.map);
            serializer.Write(this.version);
        }

        public override string ToString()
        {
            return "SystemSummaryMsg: " +
            "\nrobot: " + robot.ToString() +
            "\nmap: " + map.ToString() +
            "\nversion: " + version.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
