//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BwInterfaces
{
    [Serializable]
    public class UVKeypointMsg : Message
    {
        public const string k_RosMessageName = "bw_interfaces/UVKeypoint";
        public override string RosMessageName => k_RosMessageName;

        public float x;
        public float y;

        public UVKeypointMsg()
        {
            this.x = 0.0f;
            this.y = 0.0f;
        }

        public UVKeypointMsg(float x, float y)
        {
            this.x = x;
            this.y = y;
        }

        public static UVKeypointMsg Deserialize(MessageDeserializer deserializer) => new UVKeypointMsg(deserializer);

        private UVKeypointMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
        }

        public override string ToString()
        {
            return "UVKeypointMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
