//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZedInterfaces
{
    [Serializable]
    public class Keypoint2DfMsg : Message
    {
        public const string k_RosMessageName = "zed_interfaces/Keypoint2Df";
        public override string RosMessageName => k_RosMessageName;

        public float[] kp;

        public Keypoint2DfMsg()
        {
            this.kp = new float[2];
        }

        public Keypoint2DfMsg(float[] kp)
        {
            this.kp = kp;
        }

        public static Keypoint2DfMsg Deserialize(MessageDeserializer deserializer) => new Keypoint2DfMsg(deserializer);

        private Keypoint2DfMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.kp, sizeof(float), 2);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.kp);
        }

        public override string ToString()
        {
            return "Keypoint2DfMsg: " +
            "\nkp: " + System.String.Join(", ", kp.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
