//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZedInterfaces
{
    [Serializable]
    public class Keypoint2DiMsg : Message
    {
        public const string k_RosMessageName = "zed_interfaces/Keypoint2Di";
        public override string RosMessageName => k_RosMessageName;

        public uint[] kp;

        public Keypoint2DiMsg()
        {
            this.kp = new uint[2];
        }

        public Keypoint2DiMsg(uint[] kp)
        {
            this.kp = kp;
        }

        public static Keypoint2DiMsg Deserialize(MessageDeserializer deserializer) => new Keypoint2DiMsg(deserializer);

        private Keypoint2DiMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.kp, sizeof(uint), 2);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.kp);
        }

        public override string ToString()
        {
            return "Keypoint2DiMsg: " +
            "\nkp: " + System.String.Join(", ", kp.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
