//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZedInterfaces
{
    [Serializable]
    public class ObjectsStampedMsg : Message
    {
        public const string k_RosMessageName = "zed_interfaces/ObjectsStamped";
        public override string RosMessageName => k_RosMessageName;

        //  Standard Header
        public Std.HeaderMsg header;
        //  Array of `object_stamped` topics
        public ObjectMsg[] objects;

        public ObjectsStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.objects = new ObjectMsg[0];
        }

        public ObjectsStampedMsg(Std.HeaderMsg header, ObjectMsg[] objects)
        {
            this.header = header;
            this.objects = objects;
        }

        public static ObjectsStampedMsg Deserialize(MessageDeserializer deserializer) => new ObjectsStampedMsg(deserializer);

        private ObjectsStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.objects, ObjectMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.objects);
            serializer.Write(this.objects);
        }

        public override string ToString()
        {
            return "ObjectsStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\nobjects: " + System.String.Join(", ", objects.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
