//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ZedInterfaces
{
    [Serializable]
    public class Skeleton2DMsg : Message
    {
        public const string k_RosMessageName = "zed_interfaces/Skeleton2D";
        public override string RosMessageName => k_RosMessageName;

        //  Skeleton joints indices
        //         16-14   15-17
        //              \ /
        //               0
        //               |
        //        2------1------5
        //        |    |   |    |
        // 	    |    |   |    |
        //        3    |   |    6
        //        |    |   |    |
        //        |    |   |    |
        //        4    8   11   7
        //             |   |
        //             |   |
        //             |   |
        //             9   12
        //             |   |
        //             |   |
        //             |   |
        //            10   13
        public Keypoint2DfMsg[] keypoints;

        public Skeleton2DMsg()
        {
            this.keypoints = new Keypoint2DfMsg[18];
        }

        public Skeleton2DMsg(Keypoint2DfMsg[] keypoints)
        {
            this.keypoints = keypoints;
        }

        public static Skeleton2DMsg Deserialize(MessageDeserializer deserializer) => new Skeleton2DMsg(deserializer);

        private Skeleton2DMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.keypoints, Keypoint2DfMsg.Deserialize, 18);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.keypoints);
        }

        public override string ToString()
        {
            return "Skeleton2DMsg: " +
            "\nkeypoints: " + System.String.Join(", ", keypoints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
