string goal_type
geometry_msgs/PoseStamped goal
string target_type
string strategy
bool continuously_select_goal
---
bool success
---
bool is_done
float64 distance_to_goal
float64 time_left
float64 total_time
bw_interfaces/Trajectory trajectory
