string goal_type
geometry_msgs/PoseStamped goal
string target_type
string strategy
bool continuously_select_goal
bool overwrite_engine_config
bw_interfaces/GoalEngineConfig engine_config
float64 xy_tolerance
---
bool success
---
bool is_done
float64 distance_to_goal
float64 time_left
float64 total_time
bw_interfaces/Trajectory trajectory
