morph_kernel_size: 3
morph_iterations: 3
gaussian_kernel_size: 5
history_length: 300
var_threshold: 16
learning_rate: -1

blob_min_area: 50
min_circularity: 0.1

filter_by_area: true
filter_by_circularity: false
filter_by_convexity: false
filter_by_inertia: false
