apriltag_base_covariance_scalar: 0.001
cmd_vel_base_covariance_scalar: 0.1
process_noise: 0.001
robot_min_radius: 0.1
robot_max_radius: 0.4
estimation_topics:
    - topic: "/camera_0/estimation/robots"
      use_orientation: true
      position_covariance: 0.01
      orientation_covariance: 0.01
    - topic: "/camera_1/estimation/robots"
      use_orientation: false
      position_covariance: 0.05
tag_topics:
    - /camera_1/robot_tags
# orientation_topics:
#     mini_bot: /mini_bot/imu
