apriltag_base_covariance_scalar: 0.001
robot_estimate_base_covariance_linear_scalar: 0.001
robot_estimate_base_covariance_angular_scalar: 1.0
cmd_vel_base_covariance_scalar: 0.1
friction_factor: 0.05
process_noise: 0.001
robot_min_radius: 0.1
robot_max_radius: 0.4
