#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

PROJECT_DIR=$(realpath "${BASE_DIR}/../../")

cd ${BASE_DIR}/../resources

PERCEPTION_IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag perception)
ORGANIZATION=$(${BASE_DIR}/../get_organization)
PROJECT_NAME=$(${BASE_DIR}/../get_project_name)

VALUE=$(docker volume ls -f name=${PROJECT_NAME}_perception_build)
if ! echo ${VALUE} | grep -q "${PROJECT_NAME}_perception_build"; then
    echo "Creating perception volume"
    docker volume create ${PROJECT_NAME}_perception_build
fi

docker stop build_${PROJECT_NAME}_perception || true
docker run \
    --user ${ORGANIZATION} \
    --name build_${PROJECT_NAME}_perception \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    --env "TERM=xterm-256color" \
    -v=${PROJECT_NAME}_perception_build:/opt/${ORGANIZATION}/build:rw \
    -v=${PROJECT_DIR}:/opt/${ORGANIZATION}/${PROJECT_NAME}:rw \
    -v=${PROJECT_DIR}/scripts:/opt/${ORGANIZATION}/scripts:rw \
    --rm \
    ${PERCEPTION_IMAGE_VERSION} \
    /opt/${ORGANIZATION}/scripts/build_perception
