#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

ROBOT_NAME="${1}"
MAP_NAME="${2}"

PROJECT_DIR=$(realpath "${BASE_DIR}/../../")

${BASE_DIR}/copy_project

cd ${BASE_DIR}/../resources

IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
ORGANIZATION=$(${BASE_DIR}/../get_organization)
PROJECT_NAME=$(${BASE_DIR}/../get_project_name)
BUILD_FLAGS=-DCATKIN_BLACKLIST_PACKAGES=\'\'

docker run -it \
    --user ${ORGANIZATION} \
    --name build_${PROJECT_NAME} \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=${PROJECT_NAME}_build:/home/${ORGANIZATION}/ros_ws:rw \
    -v=${PROJECT_DIR}:/opt/${ORGANIZATION}/${PROJECT_NAME}:rw \
    -v=${PROJECT_DIR}/scripts:/opt/${ORGANIZATION}/scripts:rw \
    --rm \
    ${IMAGE_VERSION} \
    /opt/${ORGANIZATION}/scripts/build_ros_ws.sh "${BUILD_FLAGS}" "${ROBOT_NAME}" "${MAP_NAME}"
