#!/bin/bash
set -e
BASE_DIR=$(realpath "$(dirname $0)")
SELECTED_CONTAINER=$1

cd ${BASE_DIR}/../resources

export PROJECT_DIR=$(realpath "${BASE_DIR}/../../")
export PROJECT_NAME=$(${BASE_DIR}/../get_project_name)
export IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
export PERCEPTION_IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag perception)
export ORGANIZATION=$(${BASE_DIR}/../get_organization)
BUILT_IMAGES=""

if [ -z "${SELECTED_CONTAINER}" ] || [ "${SELECTED_CONTAINER}" == "ros" ]; then
    docker build \
        -f ./ros.Dockerfile \
        --build-arg PROJECT_NAME=${PROJECT_NAME} \
        --build-arg ORGANIZATION=${ORGANIZATION} \
        -t ${IMAGE_VERSION} .
    BUILT_IMAGES="${BUILT_IMAGES}\n${IMAGE_VERSION}"
    ${BASE_DIR}/build_ros_ws
fi

if [ -z "${SELECTED_CONTAINER}" ] || [ "${SELECTED_CONTAINER}" == "perception" ]; then
    docker build \
        -f ./perception.Dockerfile \
        --build-arg PROJECT_NAME=${PROJECT_NAME} \
        --build-arg ORGANIZATION=${ORGANIZATION} \
        -t ${PERCEPTION_IMAGE_VERSION} .
    BUILT_IMAGES="${BUILT_IMAGES}\n${PERCEPTION_IMAGE_VERSION}"
    ${BASE_DIR}/build_perception
fi

echo -e '\033[1mBuilt Images:\033[0m' "${BUILT_IMAGES}"

if [ -z "${SELECTED_CONTAINER}" ]; then
    HAS_GPU=$(${BASE_DIR}/has_gpu)
    ln -sf docker-compose.gpu-${HAS_GPU}.yaml docker-compose.gpu.yaml

    docker-compose \
        -f docker-compose.roscore.yml \
        -f docker-compose.${PROJECT_NAME}.yml \
        -f docker-compose.gpu.yaml \
        create
fi
