#!/bin/bash
set -e
BASE_DIR=$(realpath "$(dirname $0)")

cd ${BASE_DIR}/../resources

IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
PROJECT_NAME=$(${BASE_DIR}/../get_project_name)
ORGANIZATION=$(${BASE_DIR}/../get_organization)
PYTHON_INSTALL_VERSION=3.9
UBUNTU_VERSION_MAJOR=20
UBUNTU_VERSION_MINOR=04
CUDA_VERSION_MAJOR=12.1
CUDA_VERSION_MINOR=1
CUDNN_VERSION_MAJOR=8
docker build \
    -f ./Dockerfile \
    --build-arg ROS_DISTRO=noetic \
    --build-arg PROJECT_NAME=${PROJECT_NAME} \
    --build-arg ORGANIZATION=${ORGANIZATION} \
    --build-arg PYTHON_INSTALL_VERSION=${PYTHON_INSTALL_VERSION} \
    --build-arg UBUNTU_VERSION_MAJOR=${UBUNTU_VERSION_MAJOR} \
    --build-arg UBUNTU_VERSION_MINOR=${UBUNTU_VERSION_MINOR} \
    --build-arg CUDA_VERSION_MAJOR=${CUDA_VERSION_MAJOR} \
    --build-arg CUDA_VERSION_MINOR=${CUDA_VERSION_MINOR} \
    --build-arg CUDNN_VERSION_MAJOR=${CUDNN_VERSION_MAJOR} \
    --build-arg IMAGE_VERSION=${IMAGE_VERSION} \
    -t ${IMAGE_VERSION} .
