#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

PROJECT_DIR=$(realpath "${BASE_DIR}/../../")

${BASE_DIR}/copy_project

cd ${BASE_DIR}/../resources

IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
ORGANIZATION=$(${BASE_DIR}/../get_organization)
PROJECT_NAME=$(${BASE_DIR}/../get_project_name)

docker stop build_${PROJECT_NAME} || true
docker run \
    --user ${ORGANIZATION} \
    --name build_${PROJECT_NAME} \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    --env "TERM=xterm-256color" \
    -v=${PROJECT_NAME}_ros_build:/home/${ORGANIZATION}/ros_ws:rw \
    -v=${PROJECT_DIR}:/opt/${ORGANIZATION}/${PROJECT_NAME}:rw \
    -v=${PROJECT_DIR}/scripts:/opt/${ORGANIZATION}/scripts:rw \
    --rm \
    ${IMAGE_VERSION} \
    /opt/${ORGANIZATION}/scripts/build_ros_ws
