#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

ROBOT_NAME="${1}"
MAP_NAME="${2}"

PROJECT_NAME=$(${BASE_DIR}/../get_project_name)
declare -a CONTAINERS=("${PROJECT_NAME}_devcontainer" "${PROJECT_NAME}" "roscore")
for name in "${CONTAINERS[@]}"; do
    docker stop "${name}" || true
    docker rm "${name}" || true
done
docker volume rm ${PROJECT_NAME}_build
${BASE_DIR}/build_ros_ws "${ROBOT_NAME}" "${MAP_NAME}"
