#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

PROJECT_NAME=$(${BASE_DIR}/../get_project_name)
docker exec -it \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    ${PROJECT_NAME}_perception \
    env TERM=xterm-256color \
    /bin/bash
