#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

if [ "$EUID" -ne 0 ]
    then echo "Please run as root"
    exit
fi

set +e

readonly DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))
readonly PROJDIR="${DIR}/.."
readonly CWD="$PWD"

if ! lspci | grep -iq nvidia; then
	echo "No Nvidia card found; skipping nvidia-docker install."
	exit
fi

TARGET_DRIVER="nvidia-driver-515"
ACTUAL_DRIVER=`nvidia-detector`
# if [[ `which nvidia-detector` && ${ACTUAL_DRIVER} != ${TARGET_DRIVER} ]]; then
# 	${DIR}/lib/remove-old-gpu-drivers.sh
# fi

# Remove deprecated source files
rm /etc/apt/sources.list.d/nvidia-docker*
rm /etc/apt/sources.list.d/libnvidia*

apt-get install -y linux-headers-$(uname -r)
# apt install -y ${TARGET_DRIVER}

VERSION_ID=$(. /etc/os-release; echo $VERSION_ID | tr -d \.)

# Do not strip the . from the version here - unlike the cuda repo,
# this one needs the . in the url.
distribution=$(. /etc/os-release; echo $ID$VERSION_ID)

if [ ${VERSION_ID} -gt "2004" ]; then
    distribution="ubuntu20.04"
    echo "UNSUPPORTED! Overriding distro version."
fi

# Instructions from
# https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker
#
KEYRING_PATH="/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg"
rm -f  $KEYRING_PATH
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
	&& curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o $KEYRING_PATH \
	&& curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | \
				sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
				tee /etc/apt/sources.list.d/libnvidia-container-toolkit.list

apt-get update
# Do not ask about changing configuration files.
# https://askubuntu.com/questions/104899/make-apt-get-or-aptitude-run-with-y-but-not-prompt-for-replacement-of-configu
apt-get install --reinstall -y -o Dpkg::Options::="--force-confold" \
    libnvidia-container-tools libnvidia-container1 nvidia-docker2

systemctl try-restart docker