#!/bin/bash
set -e

SOURCE_DIR="${1:-.}"
VERSION=${2}

BASE_DIR=$(realpath "$(dirname $0)")
FILENAME=$(${BASE_DIR}/../get_archive_filename "" ${VERSION})
INPUT=${SOURCE_DIR}/${FILENAME}
echo "Loading image from ${INPUT}. This could take a while."
docker load < ${INPUT}
echo "Loaded image from ${INPUT}"

FILENAME=$(${BASE_DIR}/../get_archive_filename "perception" ${VERSION})
INPUT=${SOURCE_DIR}/${FILENAME}
echo "Loading image from ${INPUT}. This could take a while."
docker load < ${INPUT}
echo "Loaded image from ${INPUT}"
