#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

export PROJECT_DIR=$(realpath "${BASE_DIR}/../../")
export PROJECT_NAME=$(${BASE_DIR}/../get_project_name)
export IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
export PERCEPTION_IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag perception)
export ORGANIZATION=$(${BASE_DIR}/../get_organization)

HAS_GPU=$(${BASE_DIR}/has_gpu)

cd ${BASE_DIR}/../resources

ln -sf docker-compose.gpu-${HAS_GPU}.yaml docker-compose.gpu.yaml

docker-compose \
-f docker-compose.roscore.yml \
-f docker-compose.${PROJECT_NAME}.yml \
-f docker-compose.gpu.yaml \
up $@ -d
