#!/bin/bash
set -ex
BASE_DIR=$(realpath "$(dirname $0)")

if ! (devcontainer --version > /dev/null); then
	echo "Devcontainer not installed. Installing devcontainer from npm"
	npm install -g @devcontainers/cli
	nodenv rehash
fi

DEVCONTAINER_DIR=${BASE_DIR}/../../.devcontainer

devcontainer up --workspace-folder ${DEVCONTAINER_DIR} --config ${DEVCONTAINER_DIR}/ros_ws/devcontainer.json

# Run a shell in the container
${BASE_DIR}/enter_dev_container
