#!/bin/bash
set -e
BASE_DIR=$(realpath "$(dirname $0)")

REMOTE_MACHINE=$1
LAUNCH_FILE=${2:-standard.launch}

PROJECT_DIR=$(realpath "${BASE_DIR}/../../")
IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
ORGANIZATION=$(${BASE_DIR}/../get_organization)
PROJECT_NAME=$(${BASE_DIR}/../get_project_name)

docker run -it \
    --name ${ORGANIZATION}_rviz \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --env="REMOTE_MACHINE=$REMOTE_MACHINE" \
    --restart="no" \
    --net="host" \
    --privileged \
    --stop-signal=SIGINT \
    -v=${PROJECT_NAME}_build:/home/${ORGANIZATION}/ros_ws:rw \
    -v=${PROJECT_DIR}:/opt/${ORGANIZATION}/${PROJECT_NAME}:rw \
    -v=${PROJECT_DIR}/scripts:/opt/${ORGANIZATION}/scripts:rw \
    --rm \
    ${IMAGE_VERSION} \
    /opt/${ORGANIZATION}/entrypoint.sh roslaunch bw_viz ${LAUNCH_FILE}
