#!/bin/bash
set -e
BASE_DIR=$(realpath "$(dirname $0)")

if ! (devcontainer --version > /dev/null); then
	echo "Devcontainer not installed. Installing devcontainer from npm"
	npm install -g @devcontainers/cli
	nodenv rehash
fi

devcontainer up --workspace-folder ${BASE_DIR}/../..

# Run a shell in the container
${BASE_DIR}/enter_dev_container
