#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")
HOST_INTERFACE=$1

export PROJECT_DIR=$(realpath "${BASE_DIR}/../../")
export PROJECT_NAME=$(${BASE_DIR}/../get_project_name)
export IMAGE_VERSION=$(${BASE_DIR}/../get_image_tag)
export ORGANIZATION=$(${BASE_DIR}/../get_organization)
export ROS_MASTER_INTERFACE=${HOST_INTERFACE}


which nvidia-smi > /dev/null
if [[ $? -eq 1 ]]; then
	HAS_GPU="disable"
else
	nvidia-smi -L > /dev/null
	num_gpus=$?
	if ((num_gpus == 0)); then
		HAS_GPU="enable"
	else
		HAS_GPU="disable"
	fi
fi

cd ${BASE_DIR}/../resources

ln -sf docker-compose.gpu-${HAS_GPU}.yaml docker-compose.gpu.yaml

docker-compose -f docker-compose.roscore.yml -f docker-compose.${PROJECT_NAME}.yml -f docker-compose.gpu.yaml up -d
