#!/bin/bash
set -e
BASE_DIR=$(realpath "$(dirname $0)")

if ! (devcontainer --version > /dev/null); then
	echo "Devcontainer not installed. Installing devcontainer from npm"
	npm install -g @devcontainers/cli
	nodenv rehash
fi

devcontainer up --workspace-folder ${BASE_DIR}/../..

# Run a shell in the container
PROJECT_NAME=$(${BASE_DIR}/../get_project_name)
ORGANIZATION=$(${BASE_DIR}/../get_organization)
docker exec -it \
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    ${PROJECT_NAME}_devcontainer \
    env TERM=xterm-256color \
    /opt/${ORGANIZATION}/entrypoint.sh /bin/bash
