#!/bin/bash
CONTAINERS=$(docker ps -a --format "{{.Names}}" | grep -e "${PROJECT_NAME}")
if [[ ! -z ${CONTAINERS} ]]; then
    docker stop ${CONTAINERS} &> /dev/null
    docker rm ${CONTAINERS} &> /dev/null
    echo -e '\033[1mRemoved Containers:\033[0m'
    echo "${CONTAINERS}"
fi

IMAGES=$(docker image list --format "{{.Repository}}" | grep -E "vsc-true_battlebot|devcontainer|dev_container")
# don't use "" around IMAGES var to take advantage of globbing
docker rmi ${IMAGES} &> /dev/null
echo -e '\033[1mRemoved Images:\033[0m'
echo "${IMAGES}"
