#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

# SIGINT-handler
int_handler() {
    echo "Caught stop signal"
    if [ -n "$SIM_PID" ]; then
        echo "Stopping simulation"
        kill -SIGINT "${SIM_PID}"
        tail --pid="${SIM_PID}" -f /dev/null
    fi
    if [ -n "$DOCKER_PID" ]; then
        echo "Stopping docker"
        kill -SIGINT "${DOCKER_PID}"
        tail --pid="${DOCKER_PID}" -f /dev/null
    fi
    exit 0;
}
trap 'int_handler' SIGINT

RUN_HEADLESS=false
SUPPLIMENTAL_ARGS=()

for arg in "$@"; do
    if [ "$arg" == "--headless" ]; then
        RUN_HEADLESS=true
    else
        SUPPLIMENTAL_ARGS+=("$arg")
    fi
done

if [ "$RUN_HEADLESS" == true ]; then
    SIMULATION_ARGS="-nographics -batchmode"
else
    SIMULATION_ARGS=""
fi

EXTENSION=$(uname -i)
${BASE_DIR}/../TrueBattleBotSim/Build/TrueBattleBotSim.${EXTENSION} ${SIMULATION_ARGS} ${SUPPLIMENTAL_ARGS} &
SIM_PID=$!
${BASE_DIR}/../../docker/scripts/connect_sim_container &
DOCKER_PID=$!

python ${BASE_DIR}/../TrueBattleBotSim/copy_persistent_data.py
tail -F -n 1 ~/.config/unity3d/DefaultCompany/TrueBattleBotSim/Player.log
