#!/bin/bash
SUBTYPE=${1}
BASE_DIR=$(realpath "$(dirname $0)")
VERSION=${2:-$(cat ${BASE_DIR}/../image_version)}
if [ -n "${SUBTYPE}" ]; then
  SUBTYPE=_${SUBTYPE}
fi
PROJECT_NAME=$(${BASE_DIR}/get_project_name)
echo ${PROJECT_NAME}${SUBTYPE}:${VERSION}
