#!/bin/bash
set -e

PREFIX=${1}
VERSION=${2}
BASE_DIR=$(realpath "$(dirname $0)")
export IMAGE_TAG=$(${BASE_DIR}/get_image_tag ${PREFIX} ${VERSION})

python3 <<EOF
import os
import re
tag = os.environ["IMAGE_TAG"]
filename = re.sub(r"\W", "_", tag)
filename += ".tar.gz"
print(filename, end='')
EOF
