[[robots]]
name = "mini_bot"
radius = 0.1

[[robots.tags]]
tag_id = 41
tag_size = 0.1

[[robots.tags]]
tag_id = 76
tag_size = 0.1


[[robots]]
name = "main_bot"
radius = 0.15

[[robots]]
name = "referee"
team = "referee"
radius = 0.25

[[robots]]
name = "opponent_3lb"
team = "their_team"
radius = 0.1
