[[robots]]
name = "mini_bot"
radius = 0.1
is_controlled = true

[[robots.tags]]
tag_id = 41
tag_size = 0.064

[[robots.tags]]
tag_id = 76
tag_size = 0.064


[[robots]]
name = "main_bot"
team = "their_team"  # TODO: remove this before competition
radius = 0.15

[[robots]]
name = "referee"
team = "referee"
radius = 0.25

[[robots]]
name = "opponent_3lb"
team = "their_team"
radius = 0.1
