from abc import ABC
from pathlib import Path

from app.metrics.tracker.tracking_data import TrackingData

TrackedPoints = dict[tuple[int, int], dict[int, list[tuple[int, int]]]]


class TrackerInterface(ABC):
    def initialize(self, images_dir: Path) -> None: ...

    def add_track_point(self, frame_num: int, object_id: int, point: tuple[int, int]) -> None: ...

    def add_reject_point(self, frame_num: int, object_id: int, point: tuple[int, int]) -> None: ...

    def compute(self) -> None: ...

    def get_tracking(self, frame_num: int) -> TrackingData: ...

    def get_tracked_points(self) -> TrackedPoints: ...

    def reset(self) -> None: ...
