version: "3"

volumes:
    true_battlebot_ros_build:
        name: ${PROJECT_NAME}_ros_build
        external: true

    true_battlebot_perception_build:
        name: ${PROJECT_NAME}_perception_build
        external: true

services:
    true_battlebot_devcontainer:
        image: ${IMAGE_VERSION}
        container_name: ${PROJECT_NAME}_devcontainer
        restart: "no"
        network_mode: "host"
        privileged: true
        stop_signal: SIGINT
        environment:
            - DISPLAY=${DISPLAY}
            - XAUTHORITY=${XAUTHORITY}
            - IMAGE_VERSION=${IMAGE_VERSION}
        # Share IPC with the host: enables us to request X to draw things, see
        # https://askubuntu.com/questions/1237400/how-to-fix-x-error-badaccess-baddrawable-badshmseg-while-running-graphical-ap
        ipc: host
        volumes:
            - ${PROJECT_NAME}_ros_build:/home/${ORGANIZATION}/ros_ws:rw
            - ${PROJECT_DIR}:/opt/${ORGANIZATION}/${PROJECT_NAME}:rw
            - ${PROJECT_DIR}/scripts:/opt/${ORGANIZATION}/scripts:rw
            - /media/storage/true-battlebot-media:/media/storage:rw
            - /media/storage/true-battlebot-media/cache:/home/bwbots/.cache:rw
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /home/${USER}/.Xauthority:/home/${ORGANIZATION}/.Xauthority:rw
            - /home/${USER}/.gitconfig:/home/${ORGANIZATION}/.gitconfig:rw
            - /home/${USER}/.ssh:/home/${ORGANIZATION}/.ssh:rw
            - /dev:/dev:rw

        command: sleep infinity

    true_battlebot_perception_devcontainer:
        image: ${PERCEPTION_IMAGE_VERSION}
        container_name: ${PROJECT_NAME}_perception_devcontainer
        restart: "no"
        network_mode: "host"
        privileged: true
        stop_signal: SIGINT
        environment:
            - DISPLAY=${DISPLAY}
            - XAUTHORITY=${XAUTHORITY}
            - IMAGE_VERSION=${PERCEPTION_IMAGE_VERSION}
        ipc: host
        volumes:
            - ${PROJECT_NAME}_perception_build:/opt/${ORGANIZATION}/build:rw
            - ${PROJECT_DIR}:/opt/${ORGANIZATION}/${PROJECT_NAME}:rw
            - ${PROJECT_DIR}/scripts:/opt/${ORGANIZATION}/scripts:rw
            - /media/storage/true-battlebot-media:/media/storage:rw
            - /media/storage/true-battlebot-media/cache:/home/bwbots/.cache:rw
            - /media/storage/true-battlebot-media/torch-cache:/home/bwbots/.torch:rw
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /home/${USER}/.Xauthority:/home/${ORGANIZATION}/.Xauthority:rw
            - /home/${USER}/.gitconfig:/home/${ORGANIZATION}/.gitconfig:rw
            - /home/${USER}/.ssh:/home/${ORGANIZATION}/.ssh:rw
            - /dev:/dev:rw

        command: sleep infinity
