version: "3"

volumes:
  true_battlebot_build:
    name: ${PROJECT_NAME}_build
    external: true

services:
  true_battlebot_devcontainer:
    image: ${IMAGE_VERSION}
    container_name: ${PROJECT_NAME}_devcontainer
    restart: "no"
    network_mode: "host"
    privileged: true
    stop_signal: SIGINT
    ports: ["9090:9090", "10000:10000"]
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    # Share IPC with the host: enables us to request X to draw things, see
    # https://askubuntu.com/questions/1237400/how-to-fix-x-error-badaccess-baddrawable-badshmseg-while-running-graphical-ap
    ipc: host
    volumes:
      - ${PROJECT_NAME}_build:/home/${ORGANIZATION}/ros_ws:rw
      - ${PROJECT_DIR}:/opt/${ORGANIZATION}/${PROJECT_NAME}:rw
      - ${PROJECT_DIR}/scripts:/opt/${ORGANIZATION}/scripts:rw
      # TODO: mount in training data
      - /media/storage/torch-cache:/home/bwbots/.torch:rw
      - /media/storage/true-battlebot-media:/media/storage:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/${USER}/.Xauthority:/home/${ORGANIZATION}/.Xauthority:rw
      # Allow container to control docker
      - /home/${USER}/.docker:/home/${ORGANIZATION}/.docker:rw # docker looks here inside a container
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev:rw

    command: bash /opt/${ORGANIZATION}/scripts/lib/watch_for_changes.sh
