#!/bin/bash

# run the whole script from the project directory
BASE_DIR=$(realpath "$(dirname $0)")

PROJECT_DIR=$(${BASE_DIR}/get_project_dir.sh)
CHECK_DIRS=(
    "${PROJECT_DIR}/perception/detection"
    "${PROJECT_DIR}/perception/packages/perception_tools"
    "${PROJECT_DIR}/shared/bw_shared"
)

pytest ${CHECK_DIRS[@]}
