#!/bin/bash

# run the whole script from the project directory
BASE_DIR=$(realpath "$(dirname $0)")

ORG_DIR=${BASE_DIR}/../..
PROJECT_DIR=$(realpath ${ORG_DIR}/${PROJECT_NAME})
CHECK_DIRS=(
    "${PROJECT_DIR}/perception/detection"
    "${PROJECT_DIR}/perception/packages/perception_tools"
    "${PROJECT_DIR}/perception/training"
    "${PROJECT_DIR}/perception/scripts"
)

for dir in ${CHECK_DIRS[@]}; do
    cd ${dir}
    printf "\n\nValidating ${dir}\n"

    # Run formatting on python files
    ruff check .
    mypy . --disable-error-code=import-untyped --explicit-package-bases --disable-error-code=type-abstract
done
