apriltag_base_covariance_scalar: 0.00001
our_robot_estimate_base_covariance_scalar: 0.1
their_robot_estimate_base_covariance_scalar: 0.001
cmd_vel_base_covariance_scalar: 0.01
friction_factor: 0.05
process_noise: 0.001
robot_min_radius: 0.1
robot_max_radius: 0.4
