# Parameters for Stereolabs ZED2i camera
general:
    camera_model: "zed2i"
    resolution: 1 # 0 - 2.2K, 1 - 1080p, 2 - 720p, 3 - WVGA
    pub_frame_rate: 30.0
    grab_frame_rate: 30

depth:
    min_depth: 0.4 # Min: 0.2, Max: 3.0 - Default 0.7 - Note: reducing this value will require more computational power and GPU memory
    max_depth: 15.0 # Max: 40.0
    quality: 4 # '0': NONE, '1': PERFORMANCE, '2': QUALITY, '3': ULTRA, '4': NEURAL

pos_tracking:
    pos_tracking_enabled: false # True to enable positional tracking from start
    imu_fusion: true # enable/disable IMU fusion. When set to false, only the optical odometry will be used.
    publish_imu_tf: true # enable/disable the static IMU TF broadcasting
    publish_tf: false # publish `odom -> base_link` TF
    publish_map_tf: false # publish `map -> odom` TF
    base_frame: "zed_base_frame"
    map_frame: "zed_map" # main frame
    odometry_frame: "zed_odom" # odometry frame
    area_memory_db_path: "zed_area_memory.area" # file loaded when the node starts to restore the "known visual features" map.
    save_area_memory_db_on_exit: false # save the "known visual features" map when the node is correctly closed to the path indicated by `area_memory_db_path`
    area_memory: false # Enable to detect loop closure
    floor_alignment: false # Enable to automatically calculate camera/floor offset
    initial_base_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # Initial position of the `base_frame` -> [X, Y, Z, R, P, Y]
    init_odom_with_first_valid_pose: false # Enable to initialize the odometry with the first valid pose
    path_max_count: -1
    mapping_enabled: false

sensors:
    sensors_image_sync: false # Synchronize Sensors messages with latest published video/depth message
    sensors_pub_rate: 200. # frequency of publishing of sensors data. MAX: 400. - MIN: grab rate
    qos_history: 1 # '1': KEEP_LAST - '2': KEEP_ALL
    qos_depth: 1 # Queue size if using KEEP_LAST
    qos_reliability: 1 # '1': RELIABLE - '2': BEST_EFFORT -
    qos_durability: 2 # '1': TRANSIENT_LOCAL - '2': VOLATILE

object_detection:
    od_enabled: false # True to enable Object Detection [only ZED 2]
    confidence_threshold: 50.0 # [DYNAMIC] - Minimum value of the detection confidence of an object [0,100]
    model: 2 # '0': MULTI_CLASS_BOX - '1': MULTI_CLASS_BOX_ACCURATE - '2': HUMAN_BODY_FAST - '3': HUMAN_BODY_ACCURATE - '4': MULTI_CLASS_BOX_MEDIUM - '5': HUMAN_BODY_MEDIUM - '6': PERSON_HEAD_BOX
    filtering_mode: 1 # '0': NONE - '1': NMS3D - '2': NMS3D_PER_CLASS
    mc_people: true # [DYNAMIC] - Enable/disable the detection of persons for 'MULTI_CLASS_X' models
    mc_vehicle: false # [DYNAMIC] - Enable/disable the detection of vehicles for 'MULTI_CLASS_X' models
    mc_bag: false # [DYNAMIC] - Enable/disable the detection of bags for 'MULTI_CLASS_X' models
    mc_animal: false # [DYNAMIC] - Enable/disable the detection of animals for 'MULTI_CLASS_X' models
    mc_electronics: false # [DYNAMIC] - Enable/disable the detection of electronic devices for 'MULTI_CLASS_X' models
    mc_fruit_vegetable: false # [DYNAMIC] - Enable/disable the detection of fruits and vegetables for 'MULTI_CLASS_X' models
    mc_sport: false # [DYNAMIC] - Enable/disable the detection of sport-related objects for 'MULTI_CLASS_X' models
    body_fitting: true # Enable/disable body fitting for 'HUMAN_BODY_FAST' and 'HUMAN_BODY_ACCURATE' models
    body_format: 1 # '0': POSE_18 - '1': POSE_34 [Only if `HUMAN_BODY_*` model is selected]
    qos_history: 1 # '1': KEEP_LAST - '2': KEEP_ALL
    qos_depth: 1 # Queue size if using KEEP_LAST
    qos_reliability: 1 # '1': RELIABLE - '2': BEST_EFFORT
    qos_durability: 2 # '1': TRANSIENT_LOCAL - '2': VOLATILE
