#!/bin/bash
set -e

if [ "$EUID" -ne 0 ]
    then echo "Please run as root"
    exit
fi

apt-get install -y npm --no-install-recommends

npm install -g @devcontainers/cli

echo "devcontainer CLI installed."
