#!/bin/bash
DOCKERUSER=$1

if [ "$EUID" -ne 0 ]
    then echo "Please run as root"
    exit
fi


if [ -z "$DOCKERUSER" ]
    then echo "Provide user name"
    exit
fi


cd ..

apt-get remove -y docker docker-engine docker.io containerd runc docker-compose docker-compose-plugin
python3 -m pip uninstall docker-compose

apt install -y apt-transport-https ca-certificates curl \
	gnupg-agent software-properties-common

# Repo Key
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update
. /etc/os-release
if [ "$VERSION_ID" = "24.04" ]; then
  apt-get install -y \
    docker-buildx-plugin=0.27.0-1~ubuntu.24.04~noble \
    docker-ce-rootless-extras=5:28.4.0-1~ubuntu.24.04~noble \
    docker-ce=5:28.4.0-1~ubuntu.24.04~noble \
    docker-ce-cli=5:28.4.0-1~ubuntu.24.04~noble \
    containerd.io=1.7.27-1
elif [ "$VERSION_ID" = "22.04" ]; then
  apt-get install -y \
    docker-buildx-plugin=0.24.0-1~ubuntu.22.04~jammy \
    docker-ce-rootless-extras=5:28.2.2-1~ubuntu.22.04~jammy \
    docker-ce=5:28.2.2-1~ubuntu.22.04~jammy \
    docker-ce-cli=5:28.2.2-1~ubuntu.22.04~jammy \
    containerd.io=1.7.27-1
elif [ "$VERSION_ID" = "20.04" ]; then
  apt-get install -y \
    docker-buildx-plugin=0.16.2-1~ubuntu.20.04~focal \
    docker-ce-rootless-extras=5:27.1.2-1~ubuntu.20.04~focal \
    docker-ce=5:27.1.2-1~ubuntu.20.04~focal \
    docker-ce-cli=5:27.1.2-1~ubuntu.20.04~focal \
    containerd.io=1.6.24-1
else
  echo "Unsupported Ubuntu version: $VERSION_ID"
  exit 1
fi

#Install Docker Compose
export DOCKER_COMPOSE_INSTALL_PATH=/usr/local/lib/docker/cli-plugins
export DOCKER_COMPOSE_URL=https://github.com/docker/compose/releases/download/v2.37.1/docker-compose-linux-x86_64

sudo mkdir -p ${DOCKER_COMPOSE_INSTALL_PATH}
sudo curl -SL ${DOCKER_COMPOSE_URL} -o ${DOCKER_COMPOSE_INSTALL_PATH}/docker-compose
sudo chmod +x ${DOCKER_COMPOSE_INSTALL_PATH}/docker-compose
curl -fL https://raw.githubusercontent.com/docker/compose-switch/master/install_on_linux.sh | sudo sh
sudo ln -s /usr/local/bin/compose-switch /usr/local/bin/docker-compose

usermod -aG docker $DOCKERUSER
systemctl enable docker

udevadm control --reload-rules && udevadm trigger

systemctl restart docker

groupadd docker
usermod -aG docker ${DOCKERUSER}
chown "$DOCKERUSER":"$DOCKERUSER" ${HOME}/.docker -R
chmod g+rwx "${HOME}/.docker" -R
setfacl --modify user:${DOCKERUSER}:rw /var/run/docker.sock

docker login

docker run hello-world
