#!/bin/bash
BASE_DIR=$(realpath "$(dirname $0)")

sudo -v -p "Please enter the password for ${USER} host setup can do its thing: "

sudo ${BASE_DIR}/install_docker_dependencies ${USER}
sudo ${BASE_DIR}/install_nvidia_container_toolkit

sudo mkdir -p /media/storage/true-battlebot-media/logs
sudo mkdir -p /media/storage/torch-cache
sudo chown -R 1000:1000 /media/storage/torch-cache
sudo chown -R 1000:1000 /media/storage/true-battlebot-media

sudo cp ${BASE_DIR}/99-zed.rules /etc/udev/rules.d

sudo ${BASE_DIR}/install_nodenv
