version: "3"

services:
    true_battlebot_webapp:
        image: nginx
        container_name: ${PROJECT_NAME}_webapp
        restart: "no"
        ports:
            - "80:80"
        volumes:
            - ${PROJECT_DIR}/webapp:/usr/share/nginx/html:ro
            - ${PROJECT_DIR}/webapp/nginx.conf:/etc/nginx/conf.d/default.conf:ro
