version: "3"

volumes:
    true_battlebot_build:
        name: ${PROJECT_NAME}_build
        external: true

services:
    true_battlebot:
        image: ${IMAGE_VERSION}
        container_name: ${PROJECT_NAME}
        restart: "no"
        network_mode: "host"
        privileged: true
        stop_signal: SIGINT
        ports: ["9090:9090", "10000:10000"]
        environment:
            - DISPLAY=${DISPLAY}
            - XAUTHORITY=${XAUTHORITY}
            - ROS_MASTER_INTERFACE=${ROS_MASTER_INTERFACE}
        # Share IPC with the host: enables us to request X to draw things, see
        # https://askubuntu.com/questions/1237400/how-to-fix-x-error-badaccess-baddrawable-badshmseg-while-running-graphical-ap
        ipc: host
        volumes:
            - ${PROJECT_NAME}_build:/home/${ORGANIZATION}/ros_ws:rw
            - ${PROJECT_DIR}:/opt/${ORGANIZATION}/${PROJECT_NAME}:rw
            - ${PROJECT_DIR}/scripts:/opt/${ORGANIZATION}/scripts:rw
            - /media/storage/true-battlebot-media:/media/storage:rw
        command: ["/opt/${ORGANIZATION}/launch.sh"]
    true_battlebot_webapp:
        image: nginx
        container_name: ${PROJECT_NAME}_webapp
        restart: "no"
        ports:
            - "80:80"
        volumes:
            - ${PROJECT_DIR}/webapp:/usr/share/nginx/html:ro
            - ${PROJECT_DIR}/webapp/nginx.conf:/etc/nginx/conf.d/default.conf:ro
