//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ApriltagRos
{
    [Serializable]
    public class AprilTagDetectionArrayMsg : Message
    {
        public const string k_RosMessageName = "apriltag_ros/AprilTagDetectionArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public AprilTagDetectionMsg[] detections;

        public AprilTagDetectionArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.detections = new AprilTagDetectionMsg[0];
        }

        public AprilTagDetectionArrayMsg(Std.HeaderMsg header, AprilTagDetectionMsg[] detections)
        {
            this.header = header;
            this.detections = detections;
        }

        public static AprilTagDetectionArrayMsg Deserialize(MessageDeserializer deserializer) => new AprilTagDetectionArrayMsg(deserializer);

        private AprilTagDetectionArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.detections, AprilTagDetectionMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.detections);
            serializer.Write(this.detections);
        }

        public override string ToString()
        {
            return "AprilTagDetectionArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\ndetections: " + System.String.Join(", ", detections.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
