#!/bin/bash

set -e

echo "Copying project to ${ROS_WS_SRC}/${PROJECT_NAME} from /opt/${ORGANIZATION}/${PROJECT_NAME}"
sudo chown 1000:1000 "${ROS_WS_ROOT}"
mkdir -p "${ROS_WS_SRC}"
# rsync -av --delete --exclude-from=/opt/"${ORGANIZATION}"/"${PROJECT_NAME}"/ros_ws/copy_exclude.txt /opt/"${ORGANIZATION}"/"${PROJECT_NAME}"/ros_ws/ "${ROS_WS_SRC}"/"${PROJECT_NAME}"
# rsync -rtuv /opt/"${ORGANIZATION}"/"${PROJECT_NAME}"/ros_ws/bw_data/data/ "${ROS_WS_SRC}"/"${PROJECT_NAME}"/bw_data/data
# rsync -rtuv "${ROS_WS_SRC}"/"${PROJECT_NAME}"/bw_data/data/ /opt/"${ORGANIZATION}"/"${PROJECT_NAME}"/ros_ws/bw_data/data
PROJECT_ROS_SRC=/opt/"${ORGANIZATION}"/"${PROJECT_NAME}"/ros_ws/
for dir in "${PROJECT_ROS_SRC}"/*; do
    if [ -d "${dir}" ]; then
        ln -s "${dir}" "${ROS_WS_SRC}"
    fi
done
