#!/bin/bash

# run the whole script from the project directory
BASE_DIR=$(realpath "$(dirname $0)")

ORG_DIR=${BASE_DIR}/..
PROJECT_DIR=$(realpath ${ORG_DIR}/${PROJECT_NAME})
dir=$(realpath ${PROJECT_DIR}/perception/detection)

cd ${dir}
printf "\n\nFormatting ${dir}\n"

# Run formatting on python files
ruff check . --fix --select F841 --fixable F841  # Remove unused variables
ruff check . --fix --select F401 --fixable F401  # Remove unused imports
ruff format .
ruff check . --fix