#!/bin/bash
source "${BASE_ROS_WS_ROOT}"/install/setup.bash
source "${DEP_ROS_WS_ROOT}"/devel/setup.bash
cd ${ROS_WS_ROOT}
rosdep install --simulate --from-paths src --ignore-src --rosdistro=${ROS_DISTRO}
