#!/bin/bash

# run the whole script from the project directory
BASE_DIR=$(realpath "$(dirname $0)")

CHECK_DIRS=$(${BASE_DIR}/lib/get_ros_ws_check_dirs.sh $1)

for dir in ${CHECK_DIRS}; do
    printf "\n\nValidating ${dir}\n"
    cd "${dir}"

    # Run formatting on python files
    ruff check "${dir}"
    mypy "${dir}" --disable-error-code=import-untyped
done
