#!/bin/bash

# run the whole script from the project directory
BASE_DIR=$(realpath "$(dirname $0)")

ORG_DIR=${BASE_DIR}/..
PROJECT_DIR=$(realpath ${ORG_DIR}/${PROJECT_NAME})
dir=$(realpath ${PROJECT_DIR}/perception/detection)

cd ${dir}
printf "\n\nValidating ${dir}\n"

# Run formatting on python files
ruff check .
mypy . --disable-error-code=import-untyped --explicit-package-bases
