#!/bin/bash
set -e
BASE_DIR=$(realpath "$(dirname $0)")
PARENT_DIR=$(dirname $BASE_DIR)
DEVICE=$1
DESTINATION_NAME=$(${BASE_DIR}/lib/get-ip.sh ${DEVICE})
REMOTE_KEY=$(${BASE_DIR}/lib/get-key.sh ${DEVICE})
REMOTE_USER_NAME=$(${BASE_DIR}/lib/get-username.sh ${DEVICE})
ROBOT_NAME=$(${BASE_DIR}/lib/get-robot-name.sh ${DEVICE})
RESTART_SERVICE=${2:-n}
MAP_NAME=$3

LOCAL_PATH=${PARENT_DIR}
DESTINATION_PATH=/home/${REMOTE_USER_NAME}

if [ -z ${DESTINATION_NAME} ]; then
    echo "Please set a destination IP or hostname"
    exit
fi

if [ -z ${REMOTE_KEY} ]; then
    echo "Please set an SSH key file"
    exit
fi

LOCAL_PATH=$(realpath $LOCAL_PATH)
LOCAL_NAME=$(basename $LOCAL_PATH)
DEST_FULL_PATH=${DESTINATION_PATH}/${LOCAL_NAME}

${BASE_DIR}/upload ${DEVICE} n

SSH_COMMAND="ssh -i ${REMOTE_KEY} ${REMOTE_USER_NAME}@${DESTINATION_NAME}"

# build ros workspace
${SSH_COMMAND} "${DEST_FULL_PATH}/docker/scripts/build_ros_ws ${ROBOT_NAME} ${MAP_NAME}"

${BASE_DIR}/restart ${DEVICE} ${RESTART_SERVICE}
