#!/bin/bash
set -e
BASE_DIR=$(realpath "$(dirname $0)")
DEVICE=$1
DESTINATION_NAME=$(${BASE_DIR}/lib/get-ip.sh ${DEVICE})
REMOTE_KEY=$(${BASE_DIR}/lib/get-key.sh ${DEVICE})
REMOTE_USER_NAME=$(${BASE_DIR}/lib/get-username.sh ${DEVICE})
RM_PATTERN="$3"

PROJECT_NAME=$(${BASE_DIR}/../get_project_name)

if [ -z ${DESTINATION_NAME} ]; then
    echo "Please set a destination IP or hostname"
    exit
fi

if [ -z ${REMOTE_KEY} ]; then
    echo "Please set an SSH key file"
    exit
fi

SSH_COMMAND="ssh -i ${REMOTE_KEY} ${REMOTE_USER_NAME}@${DESTINATION_NAME}"

${SSH_COMMAND} -t "/home/bwbots/${PROJECT_NAME}/docker/scripts/delete_data \"${RM_PATTERN}\""
