#!/bin/bash
set -e
BASE_DIR=$(realpath "$(dirname $0)")
DEVICE=$1
DESTINATION_NAME=$(${BASE_DIR}/lib/get-ip.sh ${DEVICE})
REMOTE_KEY=$(${BASE_DIR}/lib/get-key.sh ${DEVICE})
REMOTE_USER_NAME=$(${BASE_DIR}/lib/get-username.sh ${DEVICE})
RESTART_SERVICE=${2:-y}

SERVICE_NAME=bwbots

if [ -z ${DESTINATION_NAME} ]; then
    echo "Please set a destination IP or hostname"
    exit
fi

if [ -z ${REMOTE_KEY} ]; then
    echo "Please set an SSH key file"
    exit
fi

SSH_COMMAND="ssh -i ${REMOTE_KEY} ${REMOTE_USER_NAME}@${DESTINATION_NAME}"

# restart systemd
if [ -z $RESTART_SERVICE ]; then
    echo "Restart ${SERVICE_NAME}? (Y/n) "
    read response
    case $response in
      ([Nn])     echo "Skipping restart";;
      (*)        echo "Restarting ${SERVICE_NAME}." && ${SSH_COMMAND} -t "sudo systemctl restart ${SERVICE_NAME}.service";;
    esac
else
    if [[ $RESTART_SERVICE == "n" ]]; then
        echo "Skipping restart"
    else
        echo "Restarting ${SERVICE_NAME}." && ${SSH_COMMAND} -t "sudo systemctl restart ${SERVICE_NAME}.service"
    fi
fi
