#!/bin/bash
set -e
DEVICE=$1
DESTINATION_NAME=$(${BASE_DIR}/lib/get-ip.sh ${DEVICE})
REMOTE_KEY=$(${BASE_DIR}/lib/get-key.sh ${DEVICE})
REMOTE_USER_NAME=$(${BASE_DIR}/lib/get-username.sh ${DEVICE})
ROBOT_NAME=$(${BASE_DIR}/lib/get-robot-name.sh ${DEVICE})
MAP_NAME=$2

if [ -z ${DESTINATION_NAME} ]; then
    echo "Please set a destination IP or hostname"
    exit
fi

if [ -z ${REMOTE_KEY} ]; then
    echo "Please set an SSH key file"
    exit
fi

SSH_COMMAND="ssh -i ${REMOTE_KEY} ${REMOTE_USER_NAME}@${DESTINATION_NAME}"

${SSH_COMMAND} "${DEST_FULL_PATH}/docker/scripts/set_robot ${ROBOT_NAME} ${MAP_NAME}"
