#!/bin/bash
set -e
BASE_DIR=$(realpath "$(dirname $0)")
DEVICE=$1
DESTINATION_NAME=$(${BASE_DIR}/lib/get-ip.sh ${DEVICE})
REMOTE_KEY=$(${BASE_DIR}/lib/get-key.sh ${DEVICE})
REMOTE_USER_NAME=$(${BASE_DIR}/lib/get-username.sh ${DEVICE})

LOCAL_PATH=/media/storage/true-battlebot-media/

if [ -z ${DESTINATION_NAME} ]; then
    echo "Please set a destination IP or hostname"
    exit
fi

if [ -z ${REMOTE_KEY} ]; then
    echo "Please set an SSH key file"
    exit
fi

SSH_COMMAND="ssh -i ${REMOTE_KEY} ${REMOTE_USER_NAME}@${DESTINATION_NAME}"

${SSH_COMMAND} "ls -l /media/storage/true-battlebot-media/${PATTERN}"

rsync -rtuv -e "ssh -i ${REMOTE_KEY}" ${REMOTE_USER_NAME}@${DESTINATION_NAME}:/media/storage/true-battlebot-media/${PATTERN} ${LOCAL_PATH}
