#!/bin/bash
set -e
BASE_DIR=$(realpath "$(dirname $0)")
PARENT_DIR=$(dirname $BASE_DIR)
DEVICE=$1
DESTINATION_NAME=$(${BASE_DIR}/lib/get-ip.sh ${DEVICE})
REMOTE_KEY=$(${BASE_DIR}/lib/get-key.sh ${DEVICE})
REMOTE_USER_NAME=$(${BASE_DIR}/lib/get-username.sh ${DEVICE})
RESTART_SERVICE=${2:-n}

LOCAL_PATH=${PARENT_DIR}
DESTINATION_PATH=/home/${REMOTE_USER_NAME}
LOCAL_NAME=$(basename $LOCAL_PATH)
DEST_FULL_PATH=${DESTINATION_PATH}/${LOCAL_NAME}

if [ -z ${DESTINATION_NAME} ]; then
    echo "Please set a destination IP or hostname"
    exit
fi

if [ -z ${REMOTE_KEY} ]; then
    echo "Please set an SSH key file"
    exit
fi

SSH_COMMAND="ssh -i ${REMOTE_KEY} ${REMOTE_USER_NAME}@${DESTINATION_NAME}"

# echo "Syncing time"
# ${BASE_DIR}/sync_time ${DEVICE} n

echo "Uploading package data"
rsync -av --delete --exclude-from=${LOCAL_PATH}/remote/exclude.txt  -e "ssh -i ${REMOTE_KEY}"  ${LOCAL_PATH} ${REMOTE_USER_NAME}@${DESTINATION_NAME}:${DESTINATION_PATH}

echo "Uploading data"
${BASE_DIR}/sync_data ${DEVICE} y

echo "Copying into workspace"
${SSH_COMMAND} "${DEST_FULL_PATH}/docker/scripts/copy_project"

echo "Downloading data"
${BASE_DIR}/sync_data ${DEVICE} n

${BASE_DIR}/restart ${DEVICE} ${RESTART_SERVICE}
