global_frame: odom
robot_base_frame: base_link
update_frequency: 3.0
publish_frequency: 1.0
width: 2.0
height: 2.0
# origin_x: -1.5
# origin_y: -1.5
resolution: 0.04
# static_map: false  # unnecessary with plugins
rolling_window: true

footprint_padding: 0.0

inflation:
    enabled: true
    cost_scaling_factor: 5.0
    inflation_radius: 3.0


plugins:
    - {name: static,                    type: "costmap_2d::StaticLayer"}
    # - {name: obstacle_layer,            type: "costmap_2d::VoxelLayer"}
    - {name: obstacle_layer,            type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
