### Common costmap parameters ###
global_frame: map
robot_base_frame: base_link_mini_bot
resolution: 0.05
rolling_window: false
update_frequency: 3.0
publish_frequency: 1.0
footprint_padding: 0.0

robot_radius: 0.1

transform_tolerance: 0.25 # 0.2

inflation:
    enabled: true
    cost_scaling_factor: 3.0
    inflation_radius: 1.5
