obstacle_layer:
    enabled: true
    origin_z: 0.0
    z_resolution: 0.1
    z_voxels: 10
    publish_voxel_map: false

    observation_sources: point_cloud_sensor
    point_cloud_sensor:
        sensor_frame: map
        data_type: PointCloud2
        topic: /obstacle_cloud
        marking: true
        clearing: true

        obstacle_range: 3.0
        raytrace_range: 3.0
        max_obstacle_height: 3.0
        min_obstacle_height: -3.0
        inflation_radius: 0.01
        track_unknown_space: true
        combination_method: 0

plugins:
    - { name: static, type: "costmap_2d::StaticLayer" }
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflation, type: "costmap_2d::InflationLayer" }
