### Common costmap parameters ###
global_frame: map
robot_base_frame: base_link_mini_bot

robot_radius: 0.1
footprint_padding: 0.0

inflation:
  enabled: true
  cost_scaling_factor: 3.0
  inflation_radius: 1.5

obstacle_layer:
  enabled: false

transform_tolerance: 0.25 # 0.2
