planners:
    - name: GlobalPlanner
      type: global_planner/GlobalPlanner

controllers:
    - name: TebLocalPlannerROS
      type: teb_local_planner/TebLocalPlannerROS

recovery_behaviors:
    - name: "reset_costmap"
      type: "clear_costmap_recovery/ClearCostmapRecovery"
    - name: "flail_recovery"
      type: "bw_recovery/FlailRecoveryBehavior"

reset_costmap:
    reset_distance: 5.0
    layer_names: ["obstacle_layer"]

map_frame: map
robot_frame: base_link_mini_bot

# The rate in Hz at which to run the planning loop
planner_frequency: 2.0 # 0.0

# How long the planner will wait in seconds in an attempt to find a valid plan before giving up
planner_patience: 1.0

# How many times we will recall the planner in an attempt to find a valid plan before giving up
planner_max_retries: -1

# The rate in Hz at which to run the control loop and send velocity commands to the base
controller_frequency: 20.0

# How long the controller will wait in seconds without receiving a valid control before giving up
controller_patience: 1.0

# How many times we will recall the controller in an attempt to find a valid command before giving up
controller_max_retries: -1

# Whether or not to enable the move_base_flex recovery behaviors to attempt to clear out space
recovery_enabled: true

# How much time we allow recovery behaviors to complete before canceling (or stopping if cancel fails) them
recovery_patience: 15.0

# How long in seconds to allow for oscillation before executing recovery behaviors
oscillation_timeout: 0.0

# How far in meters the robot must move to be considered not to be oscillating
oscillation_distance: 0.5
