from typing import Union

from .point_cloud_field_filter_config import PointCloudFieldFilterConfig
from .simulated_field_filter_config import SimulatedFieldFilterConfig

FieldFilterConfig = Union[PointCloudFieldFilterConfig, SimulatedFieldFilterConfig]
