# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bw_interfaces/KeypointInstance.msg. Do not edit."""
import codecs
import sys
from io import BytesIO
from typing import List, Tuple, Optional
python3 = True if sys.hexversion > 0x03000000 else False
import struct
import genpy
from bw_interfaces.msg._UVKeypoint import UVKeypoint as bw_interfaces_msg_UVKeypoint

class KeypointInstance(genpy.Message):
  _md5sum: str = "41551b51b07dbfda473dd6472d5c4530"
  _type: str = "bw_interfaces/KeypointInstance"
  _has_header: bool = False  # flag to mark the presence of a Header object
  _full_text: str = """bw_interfaces/UVKeypoint[] keypoints
string[] names
float32 score
string label
uint32 class_index
uint32 object_index

================================================================================
MSG: bw_interfaces/UVKeypoint
float32 x
float32 y
"""
  __slots__: List[str] = ['keypoints','names','score','label','class_index','object_index']
  _slot_types: List[str] = ['bw_interfaces/UVKeypoint[]','string[]','float32','string','uint32','uint32']

  def __init__(self, keypoints: List[bw_interfaces_msg_UVKeypoint] = None,
    names: List[str] = None,
    score: float = None,
    label: str = None,
    class_index: int = None,
    object_index: int = None):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
      keypoints,names,score,label,class_index,object_index

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    super(KeypointInstance, self).__init__(**{'keypoints': keypoints, 'names': names, 'score': score, 'label': label, 'class_index': class_index, 'object_index': object_index})
    if self.keypoints is None:
      self.keypoints: List[bw_interfaces_msg_UVKeypoint] = []
    else:
      self.keypoints = keypoints
    if self.names is None:
      self.names: List[str] = []
    else:
      self.names = names
    if self.score is None:
      self.score: float = 0.
    else:
      self.score = score
    if self.label is None:
      self.label: str = ''
    else:
      self.label = label
    if self.class_index is None:
      self.class_index: int = 0
    else:
      self.class_index = class_index
    if self.object_index is None:
      self.object_index: int = 0
    else:
      self.object_index = object_index

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff: BytesIO) -> None:
    """
    serialize message into buffer
    :param buff: buffer, ``BytesIO``
    """
    try:
      length = len(self.keypoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.keypoints:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
      length = len(self.names)
      buff.write(_struct_I.pack(length))
      for val1 in self.names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      _x = self.score
      buff.write(_get_struct_f().pack(_x))
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.class_index, _x.object_index))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, bytes_: bytes) -> 'KeypointInstance':
    """
    unpack serialized message in str into this message instance
    :param bytes_: byte array of serialized message, ``bytes``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.keypoints is None:
        self.keypoints = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(bytes_[start:end])
      self.keypoints = []
      for i in range(0, length):
        val1 = bw_interfaces_msg_UVKeypoint()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(bytes_[start:end])
        self.keypoints.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(bytes_[start:end])
      self.names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(bytes_[start:end])
        start = end
        end += length
        if python3:
          val1 = bytes_[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = bytes_[start:end]
        self.names.append(val1)
      start = end
      end += 4
      (self.score,) = _get_struct_f().unpack(bytes_[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(bytes_[start:end])
      start = end
      end += length
      if python3:
        self.label = bytes_[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = bytes_[start:end]
      _x = self
      start = end
      end += 8
      (_x.class_index, _x.object_index,) = _get_struct_2I().unpack(bytes_[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``BytesIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.keypoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.keypoints:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
      length = len(self.names)
      buff.write(_struct_I.pack(length))
      for val1 in self.names:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.Struct('<I%ss'%length).pack(length, val1))
      _x = self.score
      buff.write(_get_struct_f().pack(_x))
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.class_index, _x.object_index))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.keypoints is None:
        self.keypoints = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(bytes_[start:end])
      self.keypoints = []
      for i in range(0, length):
        val1 = bw_interfaces_msg_UVKeypoint()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(bytes_[start:end])
        self.keypoints.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(bytes_[start:end])
      self.names = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(bytes_[start:end])
        start = end
        end += length
        if python3:
          val1 = bytes_[start:end].decode('utf-8', 'rosmsg')
        else:
          val1 = bytes_[start:end]
        self.names.append(val1)
      start = end
      end += 4
      (self.score,) = _get_struct_f().unpack(bytes_[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(bytes_[start:end])
      start = end
      end += length
      if python3:
        self.label = bytes_[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = bytes_[start:end]
      _x = self
      start = end
      end += 8
      (_x.class_index, _x.object_index,) = _get_struct_2I().unpack(bytes_[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
