#!/bin/bash
source "${HOME}"/.base_bashrc

source /opt/ros/"${ROS_DISTRO}"/setup.bash
source "${DEP_ROS_WS_ROOT}"/devel/setup.bash
source "${ROS_WS_ROOT}"/devel/setup.bash
export ROSCONSOLE_FORMAT='[${node}] [${severity}] [${time}]: ${message}'

if [ -n "${REMOTE_MACHINE}" ]; then
    source /opt/"${ORGANIZATION}"/scripts/set_client "${REMOTE_MACHINE}"
fi
